apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system-service
  name: solar-system-service-01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solar-system
  type: ClusterIP
status:
  loadBalancer: {}
